var idName = 'Ezoza';
console.log(idName);
var surName = 'Nusratullayeva';
console.log(surName);
var age = 13;
console.log(age);
var study = 'Najottalim';
console.log(study);
var use = 'hp';
console.log(use);